import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');
const width = SCREEN_WIDTH;

const THEME = {
  PRIMARY: '#2F6E49',
  SECONDARY: '#89B882',
  ACCENT: '#F6CC63',
  BG_CREAM: '#FAF7F2',
  BG_DARK: '#090D16',
  CARD_WHITE: '#FFFFFF',
  CARD_DARK: '#121927',
  BORDER_DARK: '#1F293D',
  TEXT_DARK: '#0F172A',
  TEXT_MUTED: '#64748B',
  CORAL: '#FF6B6B',
  PURPLE: '#8E44AD',
  SKY_BLUE: '#3498DB',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: THEME.BG_CREAM,
  },
  containerDark: {
    backgroundColor: THEME.BG_DARK,
  },
  ambientBlob: {
    position: 'absolute',
    pointerEvents: 'none',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 110,
  },

  // 1. Greeting Card
  glassGreetingCard: {
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.85)',
    shadowColor: THEME.PRIMARY,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  glassGreetingDark: {
    backgroundColor: THEME.CARD_DARK,
    borderColor: THEME.BORDER_DARK,
  },
  headerCardsGrid: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  deliveringCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    paddingVertical: 4.5,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  deliveringCardDark: {
    backgroundColor: '#0F172A',
    borderColor: '#1E293B',
    shadowColor: '#000000',
    shadowOpacity: 0.2,
  },
  deliveringIconBg: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#E8F5E9',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 6,
  },
  deliveringIconBgDark: {
    backgroundColor: 'rgba(168, 85, 247, 0.15)',
  },
  deliveringTag: {
    fontSize: 9,
    fontWeight: '900',
    color: THEME.PRIMARY,
    letterSpacing: 0.5,
  },
  deliveringTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: '#0F172A',
  },
  deliveringSub: {
    fontSize: 9,
    fontWeight: '600',
    color: '#64748B',
  },
  weatherCard: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    padding: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  weatherCardDark: {
    backgroundColor: '#0F172A',
    borderColor: '#1F293D',
  },
  weatherTemp: {
    fontSize: 14,
    fontWeight: '900',
    color: '#0F172A',
  },
  weatherDesc: {
    fontSize: 9,
    fontWeight: '600',
    color: '#64748B',
  },

  // 4-Badge Feature Row
  featureBadgesRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  featureChip: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    paddingVertical: 10,
    paddingHorizontal: 4,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    gap: 4,
  },
  featureChipDark: {
    backgroundColor: THEME.CARD_DARK,
    borderColor: THEME.BORDER_DARK,
  },
  featureText: {
    fontSize: 8,
    fontWeight: '700',
    color: '#475569',
    textAlign: 'center',
  },
  greetingTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  greetingTextCol: {
    flex: 1,
    marginRight: 12,
  },
  userText: {
    fontSize: 20,
    fontWeight: '800',
    color: '#0F172A',
  },
  subGreeting: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '600',
    marginTop: 2,
  },
  themeToggleBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
  },
  glassChipsRow: {
    gap: 8,
  },
  glassChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    gap: 4,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  glassChipDark: {
    backgroundColor: '#0F172A',
    borderColor: '#334155',
  },
  glassChipText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#334155',
  },
  chipNotifDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: THEME.CORAL,
  },

  // 2. Search Capsule
  searchCapsule: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 52,
    borderRadius: 26,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    marginBottom: 20,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    shadowColor: THEME.PRIMARY,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  searchCapsuleDark: {
    backgroundColor: '#1E293B',
    borderColor: '#334155',
  },
  tickerContainer: {
    flex: 1,
    height: '100%',
    justifyContent: 'center',
    marginHorizontal: 10,
    overflow: 'hidden',
  },
  searchInputText: {
    fontSize: 13,
    fontWeight: '600',
  },
  searchActionBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 4,
  },

  // Common Headers
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 4,
  },
  titleWithBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0F172A',
  },
  sectionSub: {
    fontSize: 11,
    color: '#64748B',
    fontWeight: '600',
    marginBottom: 12,
  },
  seeAllText: {
    fontSize: 12,
    fontWeight: '800',
    color: THEME.PRIMARY,
  },

  // 3. QuickBuy Cards
  deliveryBadge: {
    backgroundColor: '#FFF3E0',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  deliveryBadgeText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#E65100',
  },
  quickBuyScroll: {
    gap: 8,
    marginBottom: 12,
    paddingVertical: 2,
  },
  quickBuyCard: {
    width: 72,
    height: 98,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 4,
    elevation: 2,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  qbImgContainer: {
    width: '100%',
    height: 52,
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  qbImg: {
    width: '100%',
    height: '100%',
  },
  qbMoreBox: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F1F5F9',
  },
  qbName: {
    fontSize: 10,
    fontWeight: '800',
    color: '#0F172A',
    textAlign: 'center',
    marginTop: 1,
  },
  qbTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    marginBottom: 2,
  },
  greenDot: {
    width: 3.5,
    height: 3.5,
    borderRadius: 2,
    backgroundColor: '#16A34A',
  },
  qbTimeText: {
    fontSize: 7.5,
    fontWeight: '800',
    color: '#16A34A',
  },

  // 4. Hero Section (Kerala Spice Banner)
  heroSection: {
    marginBottom: 20,
  },
  heroCard: {
    borderRadius: 24,
    height: 165,
    backgroundColor: '#FFFBEB',
    flexDirection: 'row',
    overflow: 'hidden',
    padding: 16,
    borderWidth: 1,
    borderColor: '#FEF3C7',
  },
  heroCardDark: {
    backgroundColor: '#1E293B',
    borderColor: '#334155',
  },
  heroContent: {
    flex: 1,
    justifyContent: 'center',
    paddingRight: 8,
  },
  heroTagRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 6,
  },
  heroTagText: {
    fontSize: 9,
    fontWeight: '900',
    color: '#DC2626',
    letterSpacing: 0.5,
  },
  heroTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: '#0F172A',
    lineHeight: 21,
    marginBottom: 4,
  },
  heroSubtitle: {
    fontSize: 10.5,
    color: '#64748B',
    fontWeight: '600',
    marginBottom: 12,
    lineHeight: 14,
  },
  heroBtn: {
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 18,
    backgroundColor: '#15803D',
  },
  heroBtnText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  heroImage: {
    width: 125,
    height: '100%',
    borderRadius: 16,
  },
  liquidDotsTrack: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 14,
    marginTop: 10,
    position: 'relative',
    alignSelf: 'center',
  },
  baseDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#CBD5E1',
    marginHorizontal: 4,
  },
  liquidPill: {
    position: 'absolute',
    left: 4,
    top: 3,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#16A34A',
  },

  // 5. Category Filter Chips
  moodChipsScroll: {
    gap: 8,
    marginBottom: 20,
    alignItems: 'center',
  },
  moodChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
  },
  moodChipText: {
    fontSize: 11.5,
    fontWeight: '800',
  },

  // 6. Shop by Vibe ✨ (Top Selection Style Container Frame)
  topSelectionContainer: {
    backgroundColor: '#93C5FD',
    borderRadius: 24,
    paddingTop: 14,
    paddingBottom: 14,
    paddingHorizontal: 12,
    marginBottom: 24,
    marginTop: 6,
    elevation: 4,
    shadowColor: '#1E40AF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
  },
  topSelectionContainerDark: {
    backgroundColor: '#1E293B',
    borderColor: '#334155',
    borderWidth: 1,
  },
  topSelectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 4,
    marginBottom: 12,
  },
  topSelectionTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  topSelectionArrowBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#0F172A',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  topSelectionInnerCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 4,
    elevation: 2,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
  },
  topSelectionInnerCardDark: {
    backgroundColor: '#0F172A',
  },
  vibeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 20,
  },
  vibeCoverCard: {
    width: 220,
    height: 220,
    borderRadius: 22,
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'flex-end',
    elevation: 6,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.4)',
  },
  vibeCoverImg: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  vibeCoverOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.42)',
  },
  vibeCoverContent: {
    padding: 14,
    zIndex: 2,
  },
  vibeCoverHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 3,
  },
  vibeCoverTitle: {
    fontSize: 14.5,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: -0.2,
    flex: 1,
    marginRight: 4,
  },
  vibeCoverEmoji: {
    fontSize: 16,
  },
  vibeCoverSub: {
    fontSize: 10.5,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.85)',
    marginBottom: 8,
  },
  vibeCoverFooterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  vibeCoverAction: {
    fontSize: 10,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  vibeCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    zIndex: 2,
  },
  vibeCardTitle: {
    fontSize: 13.5,
    fontWeight: '900',
    color: '#0F172A',
    lineHeight: 17,
  },
  vibeEmoji: {
    fontSize: 18,
    marginLeft: 6,
  },
  vibeGridImg: {
    width: '100%',
    height: 125,
    borderRadius: 16,
    marginTop: 8,
  },

  // 7. Deal of the Night 🏷️ (Dark Midnight Card)
  midnightDealSection: {
    marginBottom: 24,
  },
  midnightDealCard: {
    borderRadius: 24,
    height: 165,
    backgroundColor: '#0F172A',
    flexDirection: 'row',
    overflow: 'hidden',
    padding: 16,
    borderWidth: 1,
    borderColor: '#1E293B',
  },
  midnightDealContent: {
    flex: 1,
    justifyContent: 'center',
  },
  midnightTagRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 4,
  },
  midnightTagText: {
    fontSize: 9,
    fontWeight: '900',
    color: '#F59E0B',
    letterSpacing: 0.5,
  },
  midnightTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#FFFFFF',
    marginBottom: 2,
  },
  midnightSub: {
    fontSize: 11,
    color: '#94A3B8',
    fontWeight: '600',
  },
  midnightValidRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 2,
    marginBottom: 10,
  },
  midnightValidText: {
    fontSize: 9.5,
    color: '#64748B',
    fontWeight: '700',
  },
  midnightBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
  },
  midnightBtnText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#0F172A',
  },
  midnightImage: {
    width: 125,
    height: '100%',
    borderRadius: 16,
  },

  // 7. Spin & Win Card
  spinCard: {
    borderRadius: 24,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  spinLeft: {
    flex: 1,
  },
  spinTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#7B1FA2',
  },
  spinSub: {
    fontSize: 11,
    color: '#64748B',
    fontWeight: '600',
    marginVertical: 6,
  },
  spinBtn: {
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 16,
  },
  spinBtnText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  spinWheelIcon: {
    marginLeft: 10,
  },

  // 8. Recommended
  recProductsScroll: {
    gap: 12,
    marginBottom: 24,
  },
  recProductCard: {
    width: 140,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    padding: 8,
  },
  recProductCardDark: {
    backgroundColor: '#1E293B',
    borderColor: '#334155',
  },
  recImg: {
    width: '100%',
    height: 100,
    borderRadius: 14,
  },
  recDiscountBadge: {
    position: 'absolute',
    top: 12,
    left: 12,
    backgroundColor: '#FF6B6B',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
  },
  recDiscountText: {
    fontSize: 9,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  recHeartBtn: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  recContent: {
    marginTop: 8,
  },
  tagPill: {
    alignSelf: 'flex-start',
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    marginBottom: 4,
  },
  tagPillText: {
    fontSize: 8,
    fontWeight: '800',
    color: THEME.PRIMARY,
  },
  recTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: '#0F172A',
  },
  recPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
  },
  recPrice: {
    fontSize: 13,
    fontWeight: '900',
    color: THEME.PRIMARY,
  },
  recOldPrice: {
    fontSize: 10,
    color: '#94A3B8',
    textDecorationLine: 'line-through',
  },

  // 9. Flash Deals Spotlight
  timerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  timerBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFEBEE',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  timerText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#D32F2F',
  },
  flashFullCoverCard: {
    height: 220,
    borderRadius: 24,
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'space-between',
    marginBottom: 20,
    elevation: 8,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.22,
    shadowRadius: 14,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.4)',
  },
  flashFullCoverImg: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  flashFullCoverOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.52)',
  },
  flashTopBadgesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 14,
    zIndex: 2,
  },
  flashLiveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.75)',
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  flashLiveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#22C55E',
  },
  flashLiveText: {
    fontSize: 9,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.8,
  },
  flashDiscountPill: {
    backgroundColor: '#FF6B6B',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    elevation: 2,
  },
  flashDiscountText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  flashFullCoverContent: {
    padding: 16,
    zIndex: 2,
  },
  flashFullCoverTitle: {
    fontSize: 19,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: -0.3,
    marginBottom: 4,
  },
  flashFullCoverDesc: {
    fontSize: 11,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.85)',
    lineHeight: 15,
    marginBottom: 12,
  },
  flashFullCoverFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  flashPriceWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  flashDealPrice: {
    fontSize: 20,
    fontWeight: '900',
    color: '#22C55E',
  },
  flashOldPrice: {
    fontSize: 12,
    fontWeight: '700',
    color: 'rgba(255, 255, 255, 0.65)',
    textDecorationLine: 'line-through',
  },
  flashGrabBtn: {
    backgroundColor: '#FF6B6B',
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 20,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  flashGrabBtnText: {
    fontSize: 11.5,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },
  spotlightLeft: {
    flex: 1,
  },
  spotlightDiscountBadge: {
    backgroundColor: '#FF6B6B',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    alignSelf: 'flex-start',
    marginBottom: 6,
  },
  spotlightDiscountText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  spotlightTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0F172A',
  },
  spotlightDesc: {
    fontSize: 11,
    color: '#64748B',
    fontWeight: '600',
    marginVertical: 6,
  },
  spotlightPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  spotlightPrice: {
    fontSize: 18,
    fontWeight: '900',
    color: THEME.PRIMARY,
  },
  spotlightOldPrice: {
    fontSize: 12,
    color: '#94A3B8',
    textDecorationLine: 'line-through',
  },
  spotlightBtn: {
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 16,
  },
  spotlightBtnText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  spotlightImg: {
    width: 110,
    height: 110,
    borderRadius: 16,
  },

  // 10. Gamification Card
  gamifiedCard: {
    borderRadius: 24,
    padding: 16,
    marginBottom: 20,
  },
  gamifiedTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  levelBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  levelText: {
    fontSize: 13,
    fontWeight: '900',
    color: THEME.PURPLE,
  },
  streakBadge: {
    backgroundColor: '#FFF3E0',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  streakText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#E65100',
  },
  xpText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#64748B',
    marginBottom: 4,
  },
  xpBarBg: {
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(142, 68, 173, 0.2)',
    marginBottom: 14,
    overflow: 'hidden',
  },
  xpBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  rewardActionRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    gap: 8,
  },
  rewardActionBtn: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 10,
    alignItems: 'center',
    elevation: 2,
  },
  rewardEmoji: {
    fontSize: 18,
    marginBottom: 2,
  },
  rewardText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#0F172A',
  },

  // 11. Curated Collections (Pinterest 2x2 Grid)
  curatedGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 24,
  },
  curatedCard: {
    width: (width - 44) / 2,
    borderRadius: 24,
    padding: 12,
    borderWidth: 1,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 3,
  },
  curatedImgWrapper: {
    borderRadius: 18,
    overflow: 'hidden',
    marginBottom: 10,
  },
  curatedImg: {
    width: '100%',
    height: 110,
  },
  curatedTagBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    gap: 3,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: 'rgba(226, 232, 240, 0.6)',
  },
  curatedTagBadgeDark: {
    backgroundColor: '#121927',
    borderColor: '#1F293D',
  },
  curatedEmoji: {
    fontSize: 10,
  },
  curatedTagText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#2F6E46',
  },
  curatedTitle: {
    fontSize: 13,
    fontWeight: '900',
    color: '#0F172A',
    marginBottom: 2,
  },
  curatedPrice: {
    fontSize: 11,
    fontWeight: '800',
    color: '#2F6E46',
  },

  // 12. Plus Banner
  plusBanner: {
    borderRadius: 24,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  plusLeft: {
    flex: 1,
  },
  plusTitle: {
    fontSize: 15,
    fontWeight: '900',
    color: THEME.PURPLE,
  },
  plusSub: {
    fontSize: 10,
    color: '#64748B',
    fontWeight: '600',
    marginVertical: 4,
  },
  plusBtn: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    marginTop: 4,
  },
  plusBtnText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#FFFFFF',
  },

  // 13. Recently Viewed
  rvScroll: {
    gap: 10,
    marginBottom: 20,
  },
  rvCard: {
    width: 120,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    padding: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  rvCardDark: {
    backgroundColor: '#1E293B',
    borderColor: '#334155',
  },
  rvImg: {
    width: '100%',
    height: 80,
    borderRadius: 10,
    marginBottom: 6,
  },
  rvTagPill: {
    alignSelf: 'flex-start',
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 4,
    marginBottom: 2,
  },
  nykaaEditorialBadge: {
    fontSize: 8.5,
    fontWeight: '900',
    color: '#E91E63',
    letterSpacing: 1.5,
    marginBottom: 2,
  },
  nykaaSeeAllText: {
    fontSize: 12,
    fontWeight: '900',
    color: '#E91E63',
    letterSpacing: 0.5,
  },
  rvTagText: {
    fontSize: 7,
    fontWeight: '800',
    color: THEME.PRIMARY,
  },
  rvTitle: {
    fontSize: 10,
    fontWeight: '800',
    color: '#0F172A',
  },
  rvPrice: {
    fontSize: 11,
    fontWeight: '900',
    color: THEME.PRIMARY,
    marginTop: 2,
  },

  // 14. Trust Strip
  trustStrip: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: '#FFFFFF',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  trustStripDark: {
    backgroundColor: '#1E293B',
    borderColor: '#334155',
  },

  // ─── GEN-Z EDITORIAL DISCOVERY FEED STYLES ───
  gzEditorialBadge: {
    fontSize: 8.5,
    fontWeight: '900',
    color: '#7C3AED',
    letterSpacing: 1.5,
    marginBottom: 2,
  },
  gzSeeAllText: {
    fontSize: 12,
    fontWeight: '900',
    color: '#7C3AED',
    letterSpacing: 0.5,
  },
  discoveryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    marginTop: 22,
  },
  discoveryTitle: {
    fontSize: 16.5,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: -0.2,
  },
  discoverySub: {
    fontSize: 10.5,
    fontWeight: '600',
    color: '#64748B',
    marginTop: 1,
  },
  seeAllRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  compactRailScroll: {
    gap: 10,
    paddingVertical: 4,
    paddingRight: 16,
  },

  // ─── GEN-Z EDITORIAL PRODUCT CARD STYLES ───
  gzCard: {
    width: 156,
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 1,
    elevation: 4,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  gzCardLight: {
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(139, 92, 246, 0.15)',
  },
  gzCardDark: {
    backgroundColor: '#1E293B',
    borderColor: '#334155',
  },
  gzImgWrap: {
    width: '100%',
    height: 124,
    position: 'relative',
    backgroundColor: '#F8FAFC',
  },
  gzImg: {
    width: '100%',
    height: '100%',
  },
  gzTagBadge: {
    position: 'absolute',
    top: 6,
    left: 6,
    backgroundColor: 'rgba(124, 58, 237, 0.9)',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2.5,
  },
  gzTagText: {
    fontSize: 8,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  gzFavBtn: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  gzContent: {
    padding: 10,
  },
  gzTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 3,
  },
  gzRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    marginBottom: 6,
  },
  gzRatingText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#475569',
  },
  gzPriceAddRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  gzPrice: {
    fontSize: 12.5,
    fontWeight: '900',
    color: '#0F172A',
  },
  gzOldPrice: {
    fontSize: 9.5,
    fontWeight: '600',
    color: '#94A3B8',
    textDecorationLine: 'line-through',
  },
  gzAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    backgroundColor: '#7C3AED',
    paddingHorizontal: 9,
    paddingVertical: 4.5,
    borderRadius: 10,
  },
  gzAddBtnText: {
    fontSize: 9.5,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },

  // Nykaa Luxe Product Card
  nykaaCard: {
    width: 156,
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 1,
    elevation: 4,
    shadowColor: '#4A0E2E',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  nykaaCardLight: {
    backgroundColor: '#FAF7F2',
    borderColor: 'rgba(212, 175, 55, 0.25)',
  },
  nykaaCardDark: {
    backgroundColor: '#1E1222',
    borderColor: 'rgba(212, 175, 55, 0.3)',
  },
  nykaaImgWrap: {
    width: '100%',
    height: 124,
    position: 'relative',
    backgroundColor: '#FDFBF7',
  },
  nykaaImg: {
    width: '100%',
    height: '100%',
  },
  nykaaTagBadge: {
    position: 'absolute',
    top: 6,
    left: 6,
    backgroundColor: 'rgba(74, 14, 46, 0.85)',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderWidth: 0.5,
    borderColor: 'rgba(212, 175, 55, 0.5)',
  },
  nykaaTagText: {
    fontSize: 8,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  nykaaFavBtn: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  nykaaPriceFloatingPill: {
    position: 'absolute',
    bottom: 6,
    left: 6,
    backgroundColor: '#4A0E2E',
    borderRadius: 8,
    paddingHorizontal: 7,
    paddingVertical: 2.5,
    borderWidth: 0.5,
    borderColor: '#D4AF37',
  },
  nykaaPriceFloatingText: {
    fontSize: 10.5,
    fontWeight: '900',
    color: '#D4AF37',
  },
  nykaaContent: {
    padding: 10,
  },
  nykaaBrandSub: {
    fontSize: 8.5,
    fontWeight: '900',
    color: '#E91E63',
    letterSpacing: 1,
    marginBottom: 2,
  },
  nykaaTitle: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 6,
  },
  nykaaMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  nykaaRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  nykaaRatingText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#475569',
  },
  nykaaAddBagBtn: {
    backgroundColor: '#E91E63',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  nykaaAddBagText: {
    fontSize: 9.5,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  compactCard: {
    width: 158,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
    elevation: 3,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
  },
  compactCardDark: {
    backgroundColor: '#1E293B',
    borderColor: '#334155',
  },
  compactImgWrap: {
    width: '100%',
    height: 120,
    position: 'relative',
    backgroundColor: '#F8FAFC',
  },
  compactImg: {
    width: '100%',
    height: '100%',
  },
  compactTagBadge: {
    position: 'absolute',
    top: 6,
    left: 6,
    backgroundColor: 'rgba(15, 23, 42, 0.75)',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  compactTagText: {
    fontSize: 8.5,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  compactFavBtn: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  compactPriceFloatingPill: {
    position: 'absolute',
    bottom: 6,
    left: 6,
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    borderRadius: 8,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  compactPriceFloatingText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#38BDF8',
  },
  compactContent: {
    padding: 8,
  },
  compactTitle: {
    fontSize: 11.5,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 4,
  },
  compactMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  compactRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  compactRatingText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#475569',
  },
  compactAddBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#16A34A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Regional Heritage Hero Card (Nykaa Royal Edit)
  stateHeritageHeroCard: {
    width: '100%',
    height: 184,
    borderRadius: 24,
    overflow: 'hidden',
    marginTop: 24,
    marginBottom: 8,
    position: 'relative',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.4)',
    elevation: 5,
    shadowColor: '#4A0E2E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
  },
  stateHeritageImg: {
    width: '100%',
    height: '100%',
  },
  stateHeritageOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(30, 10, 25, 0.65)',
    padding: 18,
    justifyContent: 'flex-end',
  },
  stateBadgePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(212, 175, 55, 0.25)',
    alignSelf: 'flex-start',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginBottom: 6,
    borderWidth: 0.5,
    borderColor: '#D4AF37',
  },
  stateBadgeEmoji: {
    fontSize: 12,
  },
  stateBadgeText: {
    fontSize: 8.5,
    fontWeight: '900',
    color: '#D4AF37',
    letterSpacing: 1,
  },
  stateHeritageTitle: {
    fontSize: 18.5,
    fontWeight: '900',
    color: '#FFFFFF',
    marginBottom: 2,
    letterSpacing: -0.2,
  },
  stateHeritageSub: {
    fontSize: 11,
    color: '#F1F5F9',
    marginBottom: 10,
  },
  stateHeritageCtaRow: {
    alignSelf: 'flex-start',
  },
  stateHeritageCtaText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#D4AF37',
    letterSpacing: 0.8,
  },
  // Time-Aware Section (Nykaa Daily Edit)
  timeAwareCard: {
    borderRadius: 24,
    padding: 16,
    marginTop: 22,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.3)',
  },
  timeAwareHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  timeBadgePill: {
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  timeBadgeText: {
    fontSize: 9,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  timeSeeAllText: {
    fontSize: 11,
    fontWeight: '800',
  },
  timeAwareTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0F172A',
  },
  timeAwareSub: {
    fontSize: 11,
    color: '#475569',
  },
  // Asymmetric Lifestyle Collections Grid (Nykaa Magazine Spreads)
  asymmetricGrid: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 8,
  },
  asymmetricLeftHero: {
    flex: 1.1,
    height: 240,
    borderRadius: 24,
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.3)',
    elevation: 4,
    shadowColor: '#4A0E2E',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  asymmetricHeroImg: {
    width: '100%',
    height: '100%',
  },
  asymmetricOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(30, 10, 25, 0.6)',
    padding: 14,
    justifyContent: 'flex-end',
  },
  asymmetricBadge: {
    backgroundColor: 'rgba(212, 175, 55, 0.25)',
    alignSelf: 'flex-start',
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 3,
    marginBottom: 4,
    borderWidth: 0.5,
    borderColor: '#D4AF37',
  },
  asymmetricBadgeText: {
    fontSize: 8,
    fontWeight: '900',
    color: '#D4AF37',
    letterSpacing: 1,
  },
  asymmetricTitle: {
    fontSize: 14.5,
    fontWeight: '900',
    color: '#FFFFFF',
    lineHeight: 18,
  },
  asymmetricSub: {
    fontSize: 9.5,
    color: '#CBD5E1',
    marginTop: 2,
  },
  asymmetricRightColumn: {
    flex: 1,
    gap: 12,
  },
  asymmetricRightCard: {
    height: 114,
    borderRadius: 20,
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 1,
    borderColor: 'rgba(212, 175, 55, 0.3)',
  },
  asymmetricRightImg: {
    width: '100%',
    height: '100%',
  },
  asymmetricOverlayCompact: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(30, 10, 25, 0.55)',
    padding: 10,
    justifyContent: 'flex-end',
  },
  asymmetricBadgeTextCompact: {
    fontSize: 8,
    fontWeight: '900',
    color: '#D4AF37',
    letterSpacing: 0.8,
  },
  asymmetricTitleCompact: {
    fontSize: 12,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  trustItem: {
    alignItems: 'center',
    gap: 2,
  },
  trustText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#64748B',
  },

  // Rewards Modal
  rewardModalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 300,
  },
  rewardModalCard: {
    width: width - 64,
    borderRadius: 28,
    backgroundColor: '#FFFFFF',
    padding: 24,
    alignItems: 'center',
  },
  rewardModalDark: {
    backgroundColor: '#1E293B',
  },
  rewardModalEmoji: {
    fontSize: 48,
    marginBottom: 12,
  },
  rewardModalTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0F172A',
  },
  rewardModalSub: {
    fontSize: 12,
    color: '#64748B',
    marginVertical: 8,
  },
  rewardClaimBtn: {
    backgroundColor: THEME.PRIMARY,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 20,
    marginTop: 12,
  },
  rewardClaimText: {
    fontSize: 13,
    fontWeight: '900',
    color: '#FFFFFF',
  },

  // Toast
  floatingToastBar: {
    position: 'absolute',
    bottom: 100,
    alignSelf: 'center',
    backgroundColor: 'rgba(26, 26, 24, 0.68)',
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
    zIndex: 200,
  },
  floatingToastText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  headerIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    position: 'relative',
  },
  headerBadge: {
    position: 'absolute',
    top: -3,
    right: -3,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
  },
  headerBadgeTxt: {
    fontSize: 9,
    fontWeight: '900',
    color: '#FFFFFF',
  },

  locationChangeBtn: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#22C55E',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
  },
  locationChangeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#16A34A',
  },

  // ⚡ QUICKBUY DARK CAPSULE CARD STYLES
  quickBuyDarkContainer: {
    backgroundColor: '#090D16',
    borderRadius: 22,
    padding: 14,
    elevation: 6,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
  },
  quickBuyDarkHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    paddingHorizontal: 2,
  },
  quickBuyDarkTitleGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  quickBuyDarkTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: -0.2,
  },
  quickBuyDarkBadge: {
    backgroundColor: '#451A03',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#78350F',
  },
  quickBuyDarkBadgeText: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#FB923C',
  },
  quickBuyDarkSeeAll: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  quickBuyDarkSeeAllText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#94A3B8',
  },
  quickBuyDarkScroll: {
    gap: 12,
    paddingRight: 4,
  },
  quickBuyCircleCard: {
    alignItems: 'center',
    width: 62,
  },
  quickBuyCircleAvatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
  },
  quickBuyCircleImg: {
    width: '100%',
    height: '100%',
  },
  quickBuyCircleLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
    marginTop: 6,
  },
  quickBuyCircleTimeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    marginTop: 2,
  },
  quickBuyGreenDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#22C55E',
  },
  quickBuyCircleTimeText: {
    fontSize: 8.5,
    fontWeight: '800',
    color: '#22C55E',
  },

  // CATEGORY BADGES GRID
  categoryBadgesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 8,
    marginVertical: 12,
  },
  categoryBadgeCard: {
    width: '48.5%',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    elevation: 1,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
  },
  categoryBadgeCardDark: {
    backgroundColor: '#1E293B',
  },
  categoryBadgeIconBg: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryBadgeTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#0F172A',
  },
  categoryBadgeSub: {
    fontSize: 9.5,
    fontWeight: '600',
    color: '#64748B',
  },
  vibeScroll: {
    gap: 12,
    paddingVertical: 4,
    paddingRight: 16,
  },
  vibeDotsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginLeft: 4,
  },
  vibeDotPill: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  vibeCardSub: {
    fontSize: 9.5,
    fontWeight: '600',
    color: '#64748B',
    marginTop: 2,
  },

  // ─── HERO BANNER SKELETON STYLES ───
  heroSkeletonCard: {
    backgroundColor: '#F1F5F9',
    borderRadius: 20,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 140,
  },
  heroSkeletonCardDark: {
    backgroundColor: '#1E293B',
  },
  heroSkeletonContent: {
    flex: 1,
    marginRight: 12,
  },
  heroSkeletonTag: {
    width: 90,
    height: 12,
    backgroundColor: '#CBD5E1',
    borderRadius: 6,
    marginBottom: 10,
  },
  heroSkeletonTitle: {
    width: '85%',
    height: 18,
    backgroundColor: '#CBD5E1',
    borderRadius: 8,
    marginBottom: 8,
  },
  heroSkeletonSub: {
    width: '65%',
    height: 12,
    backgroundColor: '#CBD5E1',
    borderRadius: 6,
    marginBottom: 14,
  },
  heroSkeletonBtn: {
    width: 120,
    height: 32,
    backgroundColor: '#CBD5E1',
    borderRadius: 16,
  },
    heroSkeletonImg: {
    width: 100,
    height: 100,
    borderRadius: 16,
    backgroundColor: '#CBD5E1',
  },

  // ─── NEW CLEAN UI STYLES ───

  // Compact Header
  compactHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  compactHeaderDark: {
    backgroundColor: '#0F172A',
    borderBottomColor: '#1E293B',
  },
  compactMenuBtn: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 6,
  },
  compactLocationRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    overflow: 'hidden',
  },
  compactLocationText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#0F172A',
    maxWidth: 140,
  },
  compactHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  compactIconBtn: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  compactBadge: {
    position: 'absolute',
    top: 4,
    right: 2,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
  },
  compactBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#FFFFFF',
  },

  // Clean Scroll
  cleanScrollContent: {
    paddingTop: 12,
    paddingBottom: 110,
  },

  // Clean Search Bar
  cleanSearchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 46,
    marginHorizontal: 16,
    marginBottom: 14,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  cleanSearchBarDark: {
    backgroundColor: '#1E293B',
    borderColor: '#334155',
  },
  cleanSearchPlaceholder: {
    fontSize: 13,
    fontWeight: '500',
    color: '#94A3B8',
  },
  cleanSearchMic: {
    padding: 4,
  },

  // Category Pills
  categoryPillsRow: {
    paddingHorizontal: 16,
    gap: 8,
  },
  categoryPill: {
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  categoryPillActive: {
    backgroundColor: '#0F172A',
    borderColor: '#0F172A',
  },
  categoryPillDark: {
    backgroundColor: '#1E293B',
    borderColor: '#334155',
  },
  categoryPillText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#475569',
  },
  categoryPillTextActive: {
    color: '#FFFFFF',
  },

  // Banner Skeleton
  cleanBannerSkeleton: {
    marginHorizontal: 16,
    marginBottom: 16,
    height: 180,
    borderRadius: 16,
    backgroundColor: '#E2E8F0',
  },

  // Quick Access Grid (4 tiles)
  quickAccessGrid: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    gap: 10,
    marginTop: 16,
    marginBottom: 24,
  },
  quickAccessTile: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    gap: 6,
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  quickAccessTileDark: {
    backgroundColor: '#1E293B',
    borderColor: '#334155',
  },
  quickAccessIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickAccessLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#475569',
    textAlign: 'center',
  },

  // Section Headers
  cleanSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  cleanSectionTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  cleanSeeAll: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  cleanSeeAllText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748B',
  },

  // Product Card (horizontal rail)
  cleanProductCard: {
    width: 155,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#F1F5F9',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  cleanProductCardDark: {
    backgroundColor: '#1E293B',
    borderColor: '#334155',
  },
  cleanProductImgWrap: {
    width: '100%',
    height: 170,
    backgroundColor: '#F8FAFC',
    position: 'relative',
  },
  cleanProductImg: {
    width: '100%',
    height: '100%',
  },
  cleanWishBtn: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cleanDiscountBadge: {
    position: 'absolute',
    top: 8,
    left: 8,
    backgroundColor: '#EF4444',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 6,
  },
  cleanDiscountText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  cleanProductInfo: {
    padding: 10,
    gap: 4,
  },
  cleanProductTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#0F172A',
    lineHeight: 16,
  },
  cleanProductPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 2,
  },
  cleanProductPrice: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0F172A',
  },
  cleanProductOldPrice: {
    fontSize: 11,
    color: '#94A3B8',
    textDecorationLine: 'line-through',
    fontWeight: '500',
  },
  cleanRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  cleanRatingText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#475569',
  },

  // Flash Deal Card
  cleanFlashTimer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(244, 63, 94, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  cleanFlashTimerText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#F43F5E',
  },
  cleanFlashCard: {
    marginHorizontal: 16,
    borderRadius: 18,
    overflow: 'hidden',
    height: 220,
    position: 'relative',
  },
  cleanFlashImg: {
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  cleanFlashOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.48)',
  },
  cleanFlashBadge: {
    position: 'absolute',
    top: 14,
    left: 14,
    backgroundColor: 'rgba(255,255,255,0.15)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  cleanFlashBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  cleanFlashDiscountBadge: {
    position: 'absolute',
    top: 14,
    right: 14,
    backgroundColor: '#EF4444',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
  },
  cleanFlashDiscountText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  cleanFlashContent: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
  },
  cleanFlashTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FFFFFF',
    lineHeight: 22,
  },
  cleanFlashPrice: {
    fontSize: 18,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  cleanFlashOldPrice: {
    fontSize: 13,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.6)',
    textDecorationLine: 'line-through',
  },
  cleanFlashGrabBtn: {
    marginTop: 10,
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  cleanFlashGrabText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#0F172A',
  },

  // 2-Column Grid
  twoColGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    gap: 12,
  },
  twoColCard: {
    width: '47.5%',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#F1F5F9',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  twoColImgWrap: {
    width: '100%',
    height: 160,
    backgroundColor: '#F8FAFC',
    position: 'relative',
  },
  twoColImg: {
    width: '100%',
    height: '100%',
  },
  twoColInfo: {
    padding: 10,
    gap: 4,
  },
  twoColAddBtn: {
    marginLeft: 'auto',
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#0F172A',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Trust Strip
  cleanTrustStrip: {
    flexDirection: 'row',
    marginHorizontal: 16,
    marginTop: 28,
    marginBottom: 12,
    paddingVertical: 14,
    paddingHorizontal: 8,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    justifyContent: 'space-around',
  },
  cleanTrustItem: {
    alignItems: 'center',
    gap: 5,
    flex: 1,
  },
    cleanTrustText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#475569',
    textAlign: 'center',
  },

  // ─── REF* STYLES (Reference-image inspired) ───

  // Header
  refHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 11,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  refHeaderDark: {
    backgroundColor: '#0F172A',
    borderBottomColor: '#1E293B',
  },
  refMenuBtn: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 4,
  },
  refLocationPill: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    overflow: 'hidden',
  },
  refLocationText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1A1A2E',
    maxWidth: 150,
  },
  refHeaderIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  refIconBtn: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  refBadge: {
    position: 'absolute',
    top: 4,
    right: 2,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
  },
  refBadgeTxt: {
    fontSize: 9,
    fontWeight: '800',
    color: '#FFFFFF',
  },

  // Scroll
  refScrollContent: {
    paddingBottom: 120,
  },

  // Greeting
  refGreetingBlock: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
  },
  refGreetHello: {
    fontSize: 15,
    fontWeight: '500',
    color: '#94A3B8',
    marginBottom: 4,
  },
  refGreetQuestion: {
    fontSize: 24,
    fontWeight: '800',
    color: '#1A1A2E',
    lineHeight: 30,
    letterSpacing: -0.5,
  },

  // Search Bar
  refSearchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 48,
    marginHorizontal: 20,
    marginBottom: 16,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 14,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    gap: 10,
  },
  refSearchBarDark: {
    backgroundColor: '#1E293B',
    borderColor: '#334155',
  },
  refSearchPlaceholder: {
    flex: 1,
    fontSize: 14,
    fontWeight: '500',
    color: '#94A3B8',
  },

  // Category Pills
  refCategoryRow: {
    paddingHorizontal: 20,
    gap: 8,
  },
  refCategoryPill: {
    paddingHorizontal: 18,
    paddingVertical: 8,
    borderRadius: 22,
    backgroundColor: '#F1F5F9',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
  },
  refCategoryPillActive: {
    backgroundColor: '#1A1A2E',
    borderColor: '#1A1A2E',
  },
  refCategoryPillText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748B',
  },
  refCategoryPillTextActive: {
    color: '#FFFFFF',
  },

  // Banner skeleton
  refBannerSkeleton: {
    marginHorizontal: 20,
    marginBottom: 20,
    height: 190,
    borderRadius: 18,
    backgroundColor: '#E2E8F0',
  },

  // Quick Access Grid
  refQuickGrid: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    gap: 10,
    marginTop: 16,
    marginBottom: 24,
  },
  refQuickTile: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingVertical: 14,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#F1F5F9',
    gap: 7,
    shadowColor: '#1A1A2E',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  refQuickTileDark: {
    backgroundColor: '#1E293B',
    borderColor: '#334155',
  },
  refQuickIcon: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  refQuickLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#475569',
    textAlign: 'center',
  },

  // Section Header Row
  refSectionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 14,
  },
  refSectionTitle: {
    fontFamily: 'PlusJakartaSans-Bold',
    fontSize: 20,
    fontWeight: '700',
    color: '#1A1A2E',
    letterSpacing: -0.4,
  },
  refSeeAll: {
    fontSize: 13,
    fontWeight: '700',
    color: '#94A3B8',
  },

  // Product Card (horizontal rail — reference style)
  refProductCard: {
    width: 155,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#1A1A2E',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  refProductCardDark: {
    backgroundColor: '#1E293B',
  },
  refProductImgWrap: {
    width: '100%',
    height: 160,
    backgroundColor: '#F8FAFC',
    position: 'relative',
  },
  refProductImg: {
    width: '100%',
    height: '100%',
  },
  refHeartBtn: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(255,255,255,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  refDiscountTag: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: '#EF4444',
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 7,
  },
  refDiscountTagText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  refProductBody: {
    padding: 12,
    gap: 5,
  },
  refProductName: {
    fontFamily: Platform.select({ ios: 'Georgia', android: 'serif' }),
    fontSize: 13,
    fontWeight: '600',
    color: '#1A1A2E',
    lineHeight: 18,
  },
  refProductPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  refProductPrice: {
    fontSize: 14,
    fontWeight: '800',
    color: '#F97316',  // Orange accent — like the reference
  },
  refAddBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#1A1A2E',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Section Tabs (Mockup Style Solid Pills)
  refTabsRow: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginTop: 28,
    marginBottom: 16,
    gap: 10,
  },
  refTab: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#F1F5F9', // Light gray background for inactive
    alignItems: 'center',
    justifyContent: 'center',
  },
  refTabDark: {
    backgroundColor: 'rgba(30, 41, 59, 0.5)',
  },
  refTabActive: {
    backgroundColor: '#0F172A', // Dark navy/black for active
  },
  refTabActiveDark: {
    backgroundColor: '#FFA451', // Accent orange for active in dark mode
  },
  refTabText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#64748B',
  },
  refTabTextActive: {
    color: '#FFFFFF',
  },

  // 2-Column Grid under tabs
  refGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    gap: 12,
    marginBottom: 4,
  },
  refGridCard: {
    width: '47%',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#1A1A2E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  refGridImgWrap: {
    width: '100%',
    height: 155,
    backgroundColor: '#F8FAFC',
    position: 'relative',
  },
  refGridImg: {
    width: '100%',
    height: '100%',
  },
  refGridBody: {
    padding: 10,
    gap: 5,
  },

  // Flash Deal
  refFlashTimer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(244,63,94,0.1)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  refFlashTimerText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#F43F5E',
  },
  refFlashCard: {
    marginHorizontal: 20,
    borderRadius: 20,
    overflow: 'hidden',
    height: 230,
    position: 'relative',
    marginBottom: 4,
  },
  refFlashImg: {
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  refFlashOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  refFlashTopRow: {
    position: 'absolute',
    top: 16,
    left: 16,
    right: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  refFlashTagPill: {
    backgroundColor: 'rgba(255,255,255,0.18)',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
  },
  refFlashTagText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  refFlashDiscountPill: {
    backgroundColor: '#EF4444',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
  },
  refFlashDiscountText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  refFlashBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 18,
  },
  refFlashTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
    lineHeight: 24,
  },
  refFlashPrice: {
    fontSize: 20,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  refFlashOld: {
    fontSize: 14,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.55)',
    textDecorationLine: 'line-through',
  },
  refFlashGrabBtn: {
    marginTop: 12,
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingVertical: 9,
    borderRadius: 22,
  },
  refFlashGrabText: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1A1A2E',
  },

  // Trust Strip
  refTrustStrip: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginTop: 28,
    marginBottom: 20,
    paddingVertical: 16,
    paddingHorizontal: 10,
    borderRadius: 18,
    backgroundColor: '#FFF7F0',
    borderWidth: 1.5,
    borderColor: '#FED7AA',
    justifyContent: 'space-around',
  },
  refTrustItem: {
    alignItems: 'center',
    gap: 7,
    flex: 1,
  },
  refTrustIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: 'rgba(249,115,22,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
    refTrustText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#475569',
    textAlign: 'center',
    lineHeight: 13,
  },

  // ─── MOCKUP INSPIRED CUSTOM STYLES ───

  // Top header matching mockup
  newHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 12,
    backgroundColor: 'transparent',
  },
  newHeaderDark: {
    backgroundColor: 'transparent',
  },

  // Hero Banner Redesign
  heroBannerBackground: {
    width: '100%',
    height: 390,
    overflow: 'hidden',
  },
  heroBannerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.45)', // Premium dark slate overlay
    paddingHorizontal: 24,
    paddingBottom: 24,
    justifyContent: 'flex-end',
  },
  refGreetingBlockHero: {
    marginBottom: 12,
    alignSelf: 'stretch',
  },
  refGreetQuestionHero: {
    fontFamily: Platform.select({ ios: 'Georgia', android: 'serif' }),
    fontSize: 26,
    fontWeight: 'bold',
    lineHeight: 34,
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  translucentSearchCapsule: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.16)',
    borderRadius: 26,
    height: 52,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
  },
  translucentSearchPlaceholder: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.85)',
    marginLeft: 10,
    fontWeight: '500',
  },
  translucentSearchDivider: {
    width: 1,
    height: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    marginHorizontal: 12,
  },
  heroExploreBtn: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 22,
    paddingVertical: 10,
    borderRadius: 20,
    marginTop: 18,
    alignSelf: 'flex-start',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  heroExploreBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0F172A',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  headerExploreMoreBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFA451',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    shadowColor: '#FFA451',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 3,
  },
  headerExploreMoreText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  newCartBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.45)',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
  },
  newCartBtnDark: {
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    borderColor: 'rgba(255, 255, 255, 0.3)',
    shadowColor: '#000000',
    shadowOpacity: 0.25,
  },
  newCartIconContainer: {
    position: 'relative',
    width: 28,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  newCartBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#FFA451',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  newCartBadgeDark: {
    borderColor: '#0F172A',
  },
  newCartBadgeTxt: {
    fontSize: 9,
    fontWeight: '800',
    color: '#FFFFFF',
  },

    // iPhone-style floating capsule search bar styles
  iosSearchCapsule: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 26,
    height: 52,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    marginHorizontal: 20,
    marginTop: 16,
    marginBottom: 16,
  },
  iosSearchCapsuleDark: {
    backgroundColor: '#1E293B',
    borderColor: '#334155',
    shadowColor: '#000000',
    shadowOpacity: 0.3,
  },
  iosSearchLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    height: '100%',
    gap: 10,
  },
  iosSearchPlaceholder: {
    fontSize: 14,
    color: '#94A3B8',
    fontWeight: '500',
  },
  iosSearchDivider: {
    width: 1,
    height: 20,
    backgroundColor: '#E2E8F0',
    marginHorizontal: 8,
  },
  iosSearchFilterBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },

    // Product cards and buttons matching mockup
  refProductImgSquare: {
    width: '100%',
    height: 120,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 12,
    position: 'relative',
  },
  refProductImgInner: {
    width: 90,
    height: 90,
    borderRadius: 45,
  },
  refProductPriceNew: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFA451', // Accent orange for price matching mockup
  },
  refHeartBtnNew: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  refAddBtnOutline: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1.5,
    borderColor: '#FFA451',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFBF7',
  },

  // Active tab salad card styles (horizontal list)
  refGridCardNew: {
    width: 150,
    borderRadius: 18,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  refGridImgWrapNew: {
    width: '100%',
    height: 110,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    marginBottom: 8,
  },
  refGridImgNew: {
    width: 90,
    height: 90,
    borderRadius: 45,
  },
  refHeartBtnNewGrid: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  refGridBodyNew: {
    gap: 4,
  },
  refGridNameNew: {
    fontFamily: Platform.select({ ios: 'Georgia', android: 'serif' }),
    fontSize: 13,
    fontWeight: '700',
    color: '#272A3F',
  },
  refGridPriceRowNew: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  refGridPriceNew: {
    fontSize: 13,
    fontWeight: '800',
    color: '#FFA451',
  },
  refAddBtnSolidNew: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FFA451',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Bottom QuickBuy Footer Strip
  bottomQuickBuyStrip: {
    height: 48,
    backgroundColor: '#203437', // Slate dark green-blue color matching mockup
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    width: '100%',
  },
  bottomQuickBuyLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  bottomQuickBuyText: {
    color: '#FFFFFF',
    fontWeight: '800',
    fontSize: 13,
    letterSpacing: 0.3,
  },
  bottomQuickBuyPill: {
    backgroundColor: 'rgba(255, 164, 81, 0.15)',
    borderWidth: 1.2,
    borderColor: '#FFA451',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  bottomQuickBuyPillText: {
    color: '#FFA451',
    fontSize: 9,
    fontWeight: '800',
  },
  bottomQuickBuyRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
    bottomQuickBuySeeAll: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
  },
  refEmptyContainer: {
    width: 260,
    height: 140,
    backgroundColor: '#F8FAFC',
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    marginHorizontal: 4,
  },
  refEmptyContainerDark: {
    backgroundColor: '#1E293B',
    borderColor: '#334155',
  },
    refEmptyText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#94A3B8',
    textAlign: 'center',
    },
});
